version: "3.8"

services:
  app:
    build:
      context: . # The directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      NODE_ENV: production
    volumes:
      - .:/app # Optional: Mount the local directory for development
    restart: unless-stopped
